
import json
import sys
from pathlib import Path

notebook_path = Path(r"c:\git\automotive\notebook\07_evaluation.ipynb")

# Replacement code for CARLAEvaluator class
new_class_code = [
    "class CARLAEvaluator:\n",
    "    def __init__(self, model, shield, transform, device):\n",
    "        self.client = None\n",
    "        self.world = None\n",
    "        self.vehicle = None\n",
    "        self.camera = None\n",
    "        self.current_image = None\n",
    "        self.device = device\n",
    "        self.model = model\n",
    "        self.shield = shield\n",
    "        self.transform = transform\n",
    "        self.results = EvaluationResults()\n",
    "        \n",
    "    def connect(self, host='localhost', port=2000):\n",
    "        \"\"\"CARLA 서버 연결\"\"\"\n",
    "        try:\n",
    "            self.client = carla.Client(host, port)\n",
    "            self.client.set_timeout(10.0)\n",
    "            self.world = self.client.get_world()\n",
    "            \n",
    "            # 동기 모드 설정\n",
    "            settings = self.world.get_settings()\n",
    "            settings.synchronous_mode = True\n",
    "            settings.fixed_delta_seconds = 0.05\n",
    "            self.world.apply_settings(settings)\n",
    "            \n",
    "            print(f\"✅ CARLA 연결 성공: {self.world.get_map().name}\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"❌ 연결 실패: {e}\")\n",
    "            return False\n",
    "            \n",
    "    def spawn_vehicle(self):\n",
    "        \"\"\"차량 및 센서 스폰\"\"\"\n",
    "        bp_lib = self.world.get_blueprint_library()\n",
    "        vehicle_bp = bp_lib.find('vehicle.tesla.model3')\n",
    "        \n",
    "        spawn_points = self.world.get_map().get_spawn_points()\n",
    "        spawn_point = np.random.choice(spawn_points)\n",
    "        spawn_point.location.z += 2.0\n",
    "        \n",
    "        self.vehicle = self.world.spawn_actor(vehicle_bp, spawn_point)\n",
    "        \n",
    "        # 카메라 설정\n",
    "        camera_bp = bp_lib.find('sensor.camera.rgb')\n",
    "        camera_bp.set_attribute('image_size_x', '800')\n",
    "        camera_bp.set_attribute('image_size_y', '600')\n",
    "        camera_bp.set_attribute('fov', '100')\n",
    "        \n",
    "        camera_transform = carla.Transform(\n",
    "            carla.Location(x=1.5, z=2.4),\n",
    "            carla.Rotation(pitch=-10)\n",
    "        )\n",
    "        \n",
    "        self.camera = self.world.spawn_actor(\n",
    "            camera_bp, \n",
    "            camera_transform, \n",
    "            attach_to=self.vehicle\n",
    "        )\n",
    "        self.camera.listen(self._process_image)\n",
    "        \n",
    "        # 차량 안정화 대기\n",
    "        for _ in range(20):\n",
    "            self.world.tick()\n",
    "            \n",
    "        print(f\"✅ 차량 스폰 완료: {spawn_point.location}\")\n",
    "        \n",
    "    def _process_image(self, image):\n",
    "        array = np.frombuffer(image.raw_data, dtype=np.uint8)\n",
    "        array = array.reshape((image.height, image.width, 4))\n",
    "        self.current_image = array[:, :, :3][:, :, ::-1] # BGR to RGB\n",
    "        \n",
    "    def get_vehicle_state(self):\n",
    "        \"\"\"차량 상태 정보 수집\"\"\"\n",
    "        velocity = self.vehicle.get_velocity()\n",
    "        speed = np.sqrt(velocity.x**2 + velocity.y**2 + velocity.z**2)\n",
    "        \n",
    "        # 신호등\n",
    "        traffic_light = 'none'\n",
    "        if self.vehicle.is_at_traffic_light():\n",
    "            tl = self.vehicle.get_traffic_light()\n",
    "            state = tl.get_state()\n",
    "            if state == carla.TrafficLightState.Red:\n",
    "                traffic_light = 'red'\n",
    "            elif state == carla.TrafficLightState.Yellow:\n",
    "                traffic_light = 'yellow'\n",
    "            elif state == carla.TrafficLightState.Green:\n",
    "                traffic_light = 'green'\n",
    "        \n",
    "        return VehicleState(\n",
    "            speed=speed,\n",
    "            speed_limit=50.0,\n",
    "            traffic_light=traffic_light\n",
    "        )\n",
    "    \n",
    "    def predict_action(self, image: np.ndarray, state: VehicleState):\n",
    "        \"\"\"안전한 액션 예측\"\"\"\n",
    "        # 이미지 전처리\n",
    "        image_tensor = self.transform(image).unsqueeze(0).to(self.device)\n",
    "        \n",
    "        # 모델 예측\n",
    "        with torch.no_grad():\n",
    "            action_tensor = self.model(image_tensor)\n",
    "            action_np = action_tensor.cpu().numpy()[0]\n",
    "        \n",
    "        # 액션 값 보정 (FIXED)\n",
    "        # 1. Throttle Boosting: 정지 마찰력을 이기기 위해 2배 증폭\n",
    "        boosted_throttle = min(float(action_np[1]) * 2.0, 1.0)\n",
    "        # 2. Brake Thresholding: 0.1 미만 노이즈 제거\n",
    "        clean_brake = float(action_np[2]) if float(action_np[2]) >= 0.1 else 0.0\n",
    "        \n",
    "        policy_action = Action(\n",
    "            steer=float(action_np[0]),\n",
    "            throttle=boosted_throttle,\n",
    "            brake=clean_brake\n",
    "        )\n",
    "        \n",
    "        # Shield 적용\n",
    "        safe_action, rules = self.shield.apply(policy_action, state)\n",
    "        \n",
    "        return safe_action, rules\n",
    "    \n",
    "    def run_episode(self, max_frames=1000) -> EpisodeMetrics:\n",
    "        \"\"\"에피소드 실행\"\"\"\n",
    "        metrics = EpisodeMetrics(episode_id=len(self.results.episodes))\n",
    "        \n",
    "        self.shield.intervention_count = 0\n",
    "        start_time = time.time()\n",
    "        speeds = []\n",
    "        \n",
    "        for frame in range(max_frames):\n",
    "            self.world.tick()\n",
    "            \n",
    "            if self.current_image is None:\n",
    "                continue\n",
    "            \n",
    "            # 상태 수집\n",
    "            state = self.get_vehicle_state()\n",
    "            speeds.append(state.speed_kmh())\n",
    "            \n",
    "            # 액션 예측\n",
    "            action, rules = self.predict_action(self.current_image, state)\n",
    "            \n",
    "            # 차량 제어\n",
    "            control = carla.VehicleControl(\n",
    "                steer=action.steer,\n",
    "                throttle=action.throttle,\n",
    "                brake=action.brake\n",
    "            )\n",
    "            control.manual_gear_shift = False\n",
    "            self.vehicle.apply_control(control)\n",
    "            \n",
    "            metrics.total_frames += 1\n",
    "        \n",
    "        # 메트릭 계산\n",
    "        metrics.completion_time = time.time() - start_time\n",
    "        metrics.avg_speed = np.mean(speeds) if speeds else 0\n",
    "        metrics.shield_interventions = self.shield.intervention_count\n",
    "        metrics.success = metrics.collisions == 0\n",
    "        \n",
    "        self.results.add_episode(metrics)\n",
    "        return metrics\n",
    "    \n",
    "    def cleanup(self):\n",
    "        \"\"\"정리\"\"\"\n",
    "        if self.camera:\n",
    "            self.camera.stop()\n",
    "            self.camera.destroy()\n",
    "        if self.vehicle:\n",
    "            self.vehicle.destroy()\n",
    "\n",
    "print(\"✅ CARLAEvaluator 클래스 정의 완료 (Fix Applied)\")"
]

try:
    with open(notebook_path, 'r', encoding='utf-8') as f:
        nb_data = json.load(f)
    
    # Find the cell defining CARLAEvaluator
    patched = False
    for cell in nb_data['cells']:
        if cell['cell_type'] == 'code':
            source = cell['source']
            # Check if this cell defines the class
            if any("class CARLAEvaluator" in line for line in source):
                print("Found CARLAEvaluator cell. Patching...")
                cell['source'] = new_class_code
                patched = True
                break
    
    if patched:
        with open(notebook_path, 'w', encoding='utf-8') as f:
            json.dump(nb_data, f, indent=1)
        print("Notebook patched successfully.")
    else:
        print("Could not find CARLAEvaluator cell.")

except Exception as e:
    print(f"Error patching notebook: {e}")
